# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build Image
  inputs:
    command: buildAndPush
    containerRegistry: Harbor-Vecc-Docker
    repository: vecc/prometheus
    tags: |
      $(build.buildNumber)
      latest
    Dockerfile: Dockerfile

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
